-- MySQL Script generated by MySQL Workbench
-- Mon Sep 19 20:33:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cliente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cliente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cliente` DEFAULT CHARACTER SET utf8 ;
USE `cliente` ;

-- -----------------------------------------------------
-- Table `cliente`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`cliente` (
  `idcliente` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `contato` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`pedido` (
  `idpedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `servico` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `data_de_solicitacao` DATE NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `liberado` TINYINT NOT NULL,
  PRIMARY KEY (`idpedido`, `cliente_idcliente`),
  UNIQUE INDEX `idpedido_UNIQUE` (`idpedido` ASC) VISIBLE,
  INDEX `fk_pedido_cliente_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `cliente`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`responsavel` (
  `idresponsavel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nivel` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idresponsavel`),
  UNIQUE INDEX `idresponsavel_UNIQUE` (`idresponsavel` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`.`ordem_de_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`ordem_de_servico` (
  `idordem_de_servico` INT NOT NULL AUTO_INCREMENT,
  `status_os` VARCHAR(15) NOT NULL,
  `pedido_idpedido` INT UNSIGNED NOT NULL,
  `pedido_cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idordem_de_servico`, `pedido_idpedido`, `pedido_cliente_idcliente`),
  UNIQUE INDEX `idordem_de_servico_UNIQUE` (`idordem_de_servico` ASC) VISIBLE,
  INDEX `fk_ordem_de_servico_pedido1_idx` (`pedido_idpedido` ASC, `pedido_cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_de_servico_pedido1`
    FOREIGN KEY (`pedido_idpedido` , `pedido_cliente_idcliente`)
    REFERENCES `cliente`.`pedido` (`idpedido` , `cliente_idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`.`analise_do_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`analise_do_pedido` (
  `pedido_idpedido` INT UNSIGNED NOT NULL,
  `pedido_cliente_idcliente` INT NOT NULL,
  `responsavel_idresponsavel` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pedido_idpedido`, `pedido_cliente_idcliente`, `responsavel_idresponsavel`),
  INDEX `fk_pedido_has_responsavel_responsavel1_idx` (`responsavel_idresponsavel` ASC) VISIBLE,
  INDEX `fk_pedido_has_responsavel_pedido1_idx` (`pedido_idpedido` ASC, `pedido_cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_responsavel_pedido1`
    FOREIGN KEY (`pedido_idpedido` , `pedido_cliente_idcliente`)
    REFERENCES `cliente`.`pedido` (`idpedido` , `cliente_idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_responsavel_responsavel1`
    FOREIGN KEY (`responsavel_idresponsavel`)
    REFERENCES `cliente`.`responsavel` (`idresponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
