-- MySQL Script generated by MySQL Workbench
-- Mon Sep 19 20:27:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Forma de Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Forma de Pagamento` (
  `idForma de Pagamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Boleto Bancário` TINYINT NOT NULL,
  `Cartão de Crédito` TINYINT NOT NULL,
  `Dinheiro` TINYINT NOT NULL,
  PRIMARY KEY (`idForma de Pagamento`),
  UNIQUE INDEX `idForma de Pagamento_UNIQUE` (`idForma de Pagamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa Fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa Fisica` (
  `idPessoa Fisica` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(15) NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  `Endereço` VARCHAR(100) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Forma de Pagamento_idForma de Pagamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPessoa Fisica`, `Forma de Pagamento_idForma de Pagamento`),
  UNIQUE INDEX `idPessoa Fisica_UNIQUE` (`idPessoa Fisica` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  INDEX `fk_Pessoa Fisica_Forma de Pagamento1_idx` (`Forma de Pagamento_idForma de Pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa Fisica_Forma de Pagamento1`
    FOREIGN KEY (`Forma de Pagamento_idForma de Pagamento`)
    REFERENCES `mydb`.`Forma de Pagamento` (`idForma de Pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa Juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa Juridica` (
  `idPessoa Juridica` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CNPJ` VARCHAR(15) NOT NULL,
  `Telefone` DATETIME NOT NULL,
  `Contrato Social` VARCHAR(100) NOT NULL,
  `Endereço` VARCHAR(100) NOT NULL,
  `Forma de Pagamento_idForma de Pagamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPessoa Juridica`, `Forma de Pagamento_idForma de Pagamento`),
  UNIQUE INDEX `idPessoa Juridica_UNIQUE` (`idPessoa Juridica` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  INDEX `fk_Pessoa Juridica_Forma de Pagamento1_idx` (`Forma de Pagamento_idForma de Pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa Juridica_Forma de Pagamento1`
    FOREIGN KEY (`Forma de Pagamento_idForma de Pagamento`)
    REFERENCES `mydb`.`Forma de Pagamento` (`idForma de Pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadastro` (
  `idCadastro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(15) NOT NULL,
  `Pessoa Fisica_idPessoa Fisica` INT UNSIGNED NOT NULL,
  `Pessoa Juridica_idPessoa Juridica` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCadastro`, `Pessoa Fisica_idPessoa Fisica`, `Pessoa Juridica_idPessoa Juridica`),
  UNIQUE INDEX `idCadastro_UNIQUE` (`idCadastro` ASC) VISIBLE,
  INDEX `fk_Cadastro_Pessoa Fisica1_idx` (`Pessoa Fisica_idPessoa Fisica` ASC) VISIBLE,
  INDEX `fk_Cadastro_Pessoa Juridica1_idx` (`Pessoa Juridica_idPessoa Juridica` ASC) VISIBLE,
  CONSTRAINT `fk_Cadastro_Pessoa Fisica1`
    FOREIGN KEY (`Pessoa Fisica_idPessoa Fisica`)
    REFERENCES `mydb`.`Pessoa Fisica` (`idPessoa Fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cadastro_Pessoa Juridica1`
    FOREIGN KEY (`Pessoa Juridica_idPessoa Juridica`)
    REFERENCES `mydb`.`Pessoa Juridica` (`idPessoa Juridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Identificação` VARCHAR(15) NOT NULL,
  `Endereço` VARCHAR(100) NOT NULL,
  `Cadastro_idCadastro` INT UNSIGNED NOT NULL,
  `Cadastro_Pessoa Fisica_idPessoa Fisica` INT UNSIGNED NOT NULL,
  `Cadastro_Pessoa Juridica_idPessoa Juridica` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCliente`, `Cadastro_idCadastro`, `Cadastro_Pessoa Fisica_idPessoa Fisica`, `Cadastro_Pessoa Juridica_idPessoa Juridica`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Cliente_Cadastro1_idx` (`Cadastro_idCadastro` ASC, `Cadastro_Pessoa Fisica_idPessoa Fisica` ASC, `Cadastro_Pessoa Juridica_idPessoa Juridica` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Cadastro1`
    FOREIGN KEY (`Cadastro_idCadastro` , `Cadastro_Pessoa Fisica_idPessoa Fisica` , `Cadastro_Pessoa Juridica_idPessoa Juridica`)
    REFERENCES `mydb`.`Cadastro` (`idCadastro` , `Pessoa Fisica_idPessoa Fisica` , `Pessoa Juridica_idPessoa Juridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Status do Pedido` VARCHAR(15) NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT UNSIGNED NOT NULL,
  `Frete` FLOAT NOT NULL,
  `Status` VARCHAR(15) NOT NULL,
  `Forma de Pagamento_idForma de Pagamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`, `Forma de Pagamento_idForma de Pagamento`),
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC) VISIBLE,
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Forma de Pagamento1_idx` (`Forma de Pagamento_idForma de Pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Forma de Pagamento1`
    FOREIGN KEY (`Forma de Pagamento_idForma de Pagamento`)
    REFERENCES `mydb`.`Forma de Pagamento` (`idForma de Pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Categoria` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Razão Social` VARCHAR(100) NOT NULL,
  `CNPJ` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `idFornecedor_UNIQUE` (`idFornecedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disponibilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disponibilidade` (
  `Produto_idProduto` INT UNSIGNED NOT NULL,
  `Fornecedor_idFornecedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Fornecedor_idFornecedor`),
  INDEX `fk_Produto_has_Fornecedor_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  INDEX `fk_Produto_has_Fornecedor_Produto_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Fornecedor_Produto`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Local` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstoque`),
  UNIQUE INDEX `idEstoque_UNIQUE` (`idEstoque` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quantidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Quantidade` (
  `Produto_idProduto` INT UNSIGNED NOT NULL,
  `Estoque_idEstoque` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relação de Produto por Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relação de Produto por Pedido` (
  `Produto_idProduto` INT UNSIGNED NOT NULL,
  `Pedido_idPedido` INT UNSIGNED NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Terceiro - Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Terceiro - Vendedor` (
  `idTerceiro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Razão Social` VARCHAR(100) NOT NULL,
  `Local` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  `CNPJ` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idTerceiro`),
  UNIQUE INDEX `idTerceiro_UNIQUE` (`idTerceiro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto por vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto por vendedor` (
  `Produto_idProduto` INT UNSIGNED NOT NULL,
  `Terceiro - Vendedor_idTerceiro` INT UNSIGNED NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Terceiro - Vendedor_idTerceiro`),
  INDEX `fk_Produto_has_Terceiro - Vendedor_Terceiro - Vendedor1_idx` (`Terceiro - Vendedor_idTerceiro` ASC) VISIBLE,
  INDEX `fk_Produto_has_Terceiro - Vendedor_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Terceiro - Vendedor_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Terceiro - Vendedor_Terceiro - Vendedor1`
    FOREIGN KEY (`Terceiro - Vendedor_idTerceiro`)
    REFERENCES `mydb`.`Terceiro - Vendedor` (`idTerceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
