-- MySQL Script generated by MySQL Workbench
-- Mon Sep 19 20:28:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `idpessoa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idpessoa`),
  UNIQUE INDEX `idpessoa_UNIQUE` (`idpessoa` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `idaluno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pessoa_idpessoa` INT UNSIGNED NOT NULL,
  `matricula` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idaluno`, `pessoa_idpessoa`),
  UNIQUE INDEX `idaluno_UNIQUE` (`idaluno` ASC) VISIBLE,
  INDEX `fk_aluno_pessoa1_idx` (`pessoa_idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_pessoa1`
    FOREIGN KEY (`pessoa_idpessoa`)
    REFERENCES `mydb`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
  `iddepartamento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `campus` VARCHAR(45) NOT NULL,
  `idprofessor_coordenador` INT NOT NULL,
  PRIMARY KEY (`iddepartamento`, `idprofessor_coordenador`),
  INDEX `fk_departamento_professor1_idx` (`idprofessor_coordenador` ASC) VISIBLE,
  CONSTRAINT `fk_departamento_professor1`
    FOREIGN KEY (`idprofessor_coordenador`)
    REFERENCES `mydb`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `idprofessor` INT NOT NULL,
  `departamento_iddepartamento` INT NOT NULL,
  `pessoa_idpessoa` INT UNSIGNED NOT NULL,
  `registro` VARCHAR(45) NULL,
  `professorcol` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idprofessor`, `departamento_iddepartamento`, `pessoa_idpessoa`),
  INDEX `fk_professor_departamento1_idx` (`departamento_iddepartamento` ASC) VISIBLE,
  INDEX `fk_professor_pessoa1_idx` (`pessoa_idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_professor_departamento1`
    FOREIGN KEY (`departamento_iddepartamento`)
    REFERENCES `mydb`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_pessoa1`
    FOREIGN KEY (`pessoa_idpessoa`)
    REFERENCES `mydb`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `iddisciplina` INT NOT NULL,
  `professor_idprofessor` INT NOT NULL,
  PRIMARY KEY (`iddisciplina`, `professor_idprofessor`),
  INDEX `fk_disciplina_professor1_idx` (`professor_idprofessor` ASC) VISIBLE,
  CONSTRAINT `fk_disciplina_professor1`
    FOREIGN KEY (`professor_idprofessor`)
    REFERENCES `mydb`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `idcurso` INT NOT NULL,
  `departamento_iddepartamento` INT NOT NULL,
  PRIMARY KEY (`idcurso`, `departamento_iddepartamento`),
  INDEX `fk_curso_departamento1_idx` (`departamento_iddepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_curso_departamento1`
    FOREIGN KEY (`departamento_iddepartamento`)
    REFERENCES `mydb`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_matriculado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno_matriculado` (
  `aluno_idaluno` INT UNSIGNED NOT NULL,
  `disciplina_iddisciplina` INT NOT NULL,
  PRIMARY KEY (`aluno_idaluno`, `disciplina_iddisciplina`),
  INDEX `fk_aluno_has_disciplina_disciplina1_idx` (`disciplina_iddisciplina` ASC) VISIBLE,
  INDEX `fk_aluno_has_disciplina_aluno_idx` (`aluno_idaluno` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_disciplina_aluno`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `mydb`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_iddisciplina`)
    REFERENCES `mydb`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina_e_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina_e_curso` (
  `curso_idcurso` INT NOT NULL,
  `disciplina_iddisciplina` INT NOT NULL,
  PRIMARY KEY (`curso_idcurso`, `disciplina_iddisciplina`),
  INDEX `fk_curso_has_disciplina_disciplina1_idx` (`disciplina_iddisciplina` ASC) VISIBLE,
  INDEX `fk_curso_has_disciplina_curso1_idx` (`curso_idcurso` ASC) VISIBLE,
  CONSTRAINT `fk_curso_has_disciplina_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `mydb`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_iddisciplina`)
    REFERENCES `mydb`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pre_requisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pre_requisitos` (
  `idpre_requisitos` INT NOT NULL,
  PRIMARY KEY (`idpre_requisitos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pre_requisito_da_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pre_requisito_da_disciplina` (
  `disciplina_iddisciplina` INT NOT NULL,
  `pre_requisitos_idpre_requisitos` INT NOT NULL,
  PRIMARY KEY (`disciplina_iddisciplina`, `pre_requisitos_idpre_requisitos`),
  INDEX `fk_disciplina_has_pre_requisitos_pre_requisitos1_idx` (`pre_requisitos_idpre_requisitos` ASC) VISIBLE,
  INDEX `fk_disciplina_has_pre_requisitos_disciplina1_idx` (`disciplina_iddisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_disciplina_has_pre_requisitos_disciplina1`
    FOREIGN KEY (`disciplina_iddisciplina`)
    REFERENCES `mydb`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina_has_pre_requisitos_pre_requisitos1`
    FOREIGN KEY (`pre_requisitos_idpre_requisitos`)
    REFERENCES `mydb`.`pre_requisitos` (`idpre_requisitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`periodo` (
  `idperiodo` INT UNSIGNED NOT NULL,
  `ano` INT(4) NOT NULL,
  `semestre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idperiodo`),
  UNIQUE INDEX `idperiodo_UNIQUE` (`idperiodo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina_por_periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina_por_periodo` (
  `disciplina_iddisciplina` INT NOT NULL,
  `disciplina_professor_idprofessor` INT NOT NULL,
  `periodo_idperiodo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`disciplina_iddisciplina`, `disciplina_professor_idprofessor`, `periodo_idperiodo`),
  INDEX `fk_disciplina_has_periodo_periodo1_idx` (`periodo_idperiodo` ASC) VISIBLE,
  INDEX `fk_disciplina_has_periodo_disciplina1_idx` (`disciplina_iddisciplina` ASC, `disciplina_professor_idprofessor` ASC) VISIBLE,
  CONSTRAINT `fk_disciplina_has_periodo_disciplina1`
    FOREIGN KEY (`disciplina_iddisciplina` , `disciplina_professor_idprofessor`)
    REFERENCES `mydb`.`disciplina` (`iddisciplina` , `professor_idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina_has_periodo_periodo1`
    FOREIGN KEY (`periodo_idperiodo`)
    REFERENCES `mydb`.`periodo` (`idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`extensao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`extensao` (
  `idextensao` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  `instituicao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idextensao`),
  UNIQUE INDEX `idextensao_UNIQUE` (`idextensao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_matriculado_has_extensao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno_matriculado_has_extensao` (
  `aluno_matriculado_aluno_idaluno` INT UNSIGNED NOT NULL,
  `aluno_matriculado_disciplina_iddisciplina` INT NOT NULL,
  `extensao_idextensao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`aluno_matriculado_aluno_idaluno`, `aluno_matriculado_disciplina_iddisciplina`, `extensao_idextensao`),
  INDEX `fk_aluno_matriculado_has_extensao_extensao1_idx` (`extensao_idextensao` ASC) VISIBLE,
  INDEX `fk_aluno_matriculado_has_extensao_aluno_matriculado1_idx` (`aluno_matriculado_aluno_idaluno` ASC, `aluno_matriculado_disciplina_iddisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_matriculado_has_extensao_aluno_matriculado1`
    FOREIGN KEY (`aluno_matriculado_aluno_idaluno` , `aluno_matriculado_disciplina_iddisciplina`)
    REFERENCES `mydb`.`aluno_matriculado` (`aluno_idaluno` , `disciplina_iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_matriculado_has_extensao_extensao1`
    FOREIGN KEY (`extensao_idextensao`)
    REFERENCES `mydb`.`extensao` (`idextensao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
